# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

{
  imports =
    [
# Files made to be used by many systems
      ./modules/global/docker.nix
      ./modules/global/hardware.nix
      ./modules/global/ollama.nix
      ./modules/global/ssh.nix
      ./modules/global/vm.nix
      ./modules/global/wine.nix
# Device specific Configuration
  # For device "loq"
      #./modules/loq/backup.nix #incomplete
      # For wayland, xwayland, display managers, window managers, lockscreens
      ./modules/loq/display.nix
      # Generated by nixos-generate-config. Modified to match changes in system
      ./modules/loq/hardware-configuration.nix
      # Additional personally made hardware configuration
      ./modules/loq/hardware.nix
      ./modules/loq/network.nix
      ./modules/loq/nvidia.nix
      # For programs available via root
      ./modules/loq/pkgs.nix
      ./modules/loq/security.nix
      # For managing secrets
      ./sops.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Set your time zone.
  time.timeZone = "Asia/Qatar";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.incogshift = {
    isNormalUser = true;
    description = "incogshift";
    extraGroups = [ "networkmanager" "wheel" "adb" ];
    shell = pkgs.zsh;
  };
  programs.zsh.enable = true;

  home-manager = {
    # also pass inputs to home-manager modules
    extraSpecialArgs = {
      inherit inputs;
      inherit pkgs;
    };
    users = {
      "incogshift" = import ./home.nix;
    };
    useUserPackages = true;
  };
}
