# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

{
  imports =
    [
# "./modules/global": modules made to be used by many systems
# "./modules/<hostname>": modules made to be used by specific hosts

      ./modules/global/docker.nix
      ./modules/global/nix.nix
      ./modules/global/ollama.nix
      ./modules/global/ssh.nix
      ./modules/global/user.nix
      ./modules/global/vm.nix
      ./modules/global/wine.nix
      ./modules/loq/network.nix
      ./modules/loq/nvidia.nix
      ./modules/loq/security.nix

      # For programs available via root
      ./modules/loq/pkgs.nix

      # For managing secrets
      ./sops.nix

      #./modules/loq/backup.nix #incomplete

      # Generated by nixos-generate-config. Modified to match changes in system
      ./modules/loq/hardware-configuration.nix
      # Additional personally made hardware configuration
      ./modules/global/hardware.nix
      ./modules/loq/hardware.nix
      ./modules/global/boot.nix
      ./modules/loq/keyboard.nix

      # For wayland, xwayland, display managers, window managers, lockscreens
      ./modules/loq/display.nix
    ];
  
# What follows is base system setup

  # Set your time zone.
  time.timeZone = "Asia/Qatar";

  home-manager = {
    # also pass inputs to home-manager modules
    extraSpecialArgs = {
      inherit inputs;
      inherit pkgs;
    };
    users = {
      "incogshift" = import ./home.nix;
    };
    useUserPackages = true;
  };
}
