# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/582aeada-98c6-4c57-b9dd-8f5046ac4612";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9cb8e2e0-3b01-4305-af8e-874b5893d1e5".device = "/dev/disk/by-uuid/9cb8e2e0-3b01-4305-af8e-874b5893d1e5";

  fileSystems."/st" =
    { device = "/dev/disk/by-uuid/ecb2e3b3-cdc3-49b5-abf5-354140bbf409";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."st".device = "/dev/disk/by-uuid/82dc2399-d215-441e-aed4-1a488a1a1727";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D340-65A5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/55f38380-144e-4080-a575-cf3650dd4d2e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
