# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Decoration and Animations Settings
# Hyprland Wiki Links
# Animation - https://wiki.hyprland.org/Configuring/Animations/
# Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

general {
  border_size = 1
  gaps_in = 1
  gaps_out = 1
}

#b Smart gaps [v0.49]
  workspace = w[tv1], gapsout:0, gapsin:0
  workspace = f[1], gapsout:0, gapsin:0
  windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
  windowrule = rounding 0, floating:0, onworkspace:w[tv1]
  windowrule = bordersize 0, floating:0, onworkspace:f[1]
  windowrule = rounding 0, floating:0, onworkspace:f[1]
#e

decoration {
  rounding = 8
  blur {
    enabled = true
    size = 10
    passes = 3
    ignore_opacity = true
    new_optimizations = true
    #special = true
    noise = 0.10
    brightness = 0.90
  }
}

animations {
  enabled = no
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = true
  enable_hyprcursor = true
  warp_on_change_workspace = 0
  no_warps = true
}

