
plugin {
  hyprtasking {
    layout = grid
    gap_size = 0
    bg_color = 0xff26233a
    border_size = 1
    gestures {
      enabled = false
      open_fingers = 3
      open_distance = 300
      open_positive = true
    }
    grid {
      rows = 3
      cols = 3
    }
    linear {
      height = 400
      scroll_speed = 1.1
      blur = 0
    }
  }
}

# plugins
#bind = SUPER, A, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable

bind = SUPER, A, hyprtasking:toggle, cursor
bind = SUPER SHIFT, A, hyprtasking:toggle, all
bind = SUPER SHIFT, H, hyprtasking:move, left
bind = SUPER SHIFT, J, hyprtasking:move, down
bind = SUPER SHIFT, K, hyprtasking:move, up
bind = SUPER SHIFT, L, hyprtasking:move, right

#bind = SUPER, X, hyprtasking:killhovered
