# Keybinds
source = ./hyprland-dot-conf/keybinds.conf

# general
source = ./hyprland-dot-conf/general.conf

# Startup and environmental variables
source = ./hyprland-dot-conf/startup.conf

# Plugins
source = ./hyprland-dot-conf/plugins.conf

# monitor-rules
source = ./hyprland-dot-conf/hardware.conf

# Decoration and Animations Settings
source = ./hyprland-dot-conf/decor.conf
